spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 指定数据库驱动
    # 数据库连接信息
    url: jdbc:mysql://127.0.0.1:3306/xiaohashu?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    # 改为加密后的密码
    password: gSJp414d7TCz0SDxV8DXfxeV7iY8laa805nJmhW/H/4wIL6z+rsBjnro0PhA1u9RgpNHZlVKoe/WulXkcSP21g==
    # 配置数据库连接池 使用 阿里云的 德鲁伊 druid
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid 连接池
    druid:
      initial-size: 5 # 初始化连接池大小
      min-idle: 5 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 6000 # 连接时最大等待时间 单位：毫秒
      test-while-idle: true
      time-between-eviction-runs-millis: 6000 # 配置多久进行一次检测，检测需要关闭的连接 毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在连接池中最小生存的时间 毫秒
      max-evictable-idle-time-millis: 900000 # 配置一个连接在连接池中最大生存的时间 毫秒
      validation-query: SELECT 1 FROM DUAL # 配置测试连接是否可用的查询
      test-on-borrow: false # 连接从连接池获取时是否测试连接的可用性
      test-on-return: false # 连接返回连接池时是否测试连接的可用性
      pool-prepared-statements: false # 是否缓存 PreparedStatement 默认为false
      web-stat-filter: # 用于配置Druid的web监控功能，enabled代表启用
        enabled: true
      stat-view-servlet: # 配置druid后台监控的访问路径，登录用户名和密码
        enabled: true
        url-pattern: /druid/* # 配置监控后台访问的路径
        login-username: admin # 配置监控后台登录的用户名、密码
        login-password: admin
      filter: # druid 的过滤器，包括统计过滤器和防火墙过滤器
        config:
          enabled: true # 开启密码解密的配置项
        stat: # 配置统计过滤器
          enabled: true # 开启统计功能
          log-slow-sql: true # 开启慢sql 记录
          slow-sql-millis: 2000 # 若执行耗时大于 2s，则视为慢sql
          merge-sql: true # 是否开启sql合并功能
        wall: # 防火墙 防止sql注入
          config:
            multi-statement-allow: true # 允许执行多条sql语句
      # 标识开启密码解密功能，key时公钥
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANb4MT3DFtDPwIMd2HNBZXL12qSqqSi9w/hL9kJgxsJW+qncGLqXYWsm5i9MdUHfhALxl+PE0q97CPbWCbrxRLsCAwEAAQ==
  data:
    redis:
      database: 0 # Redis 数据库索引 默认为0
      host: 127.0.0.1 # redis 服务器地址
      port: 6379
      password: admin888 # redis服务器连接密码，默认为空
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 连接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间 使用负值表示没有限制
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接

# 日志配置
logging:
  level:
    # 方便测试，打印实际执行的SQL语句，配置 mapper 接口所在的包的日志级别为debug即可
    top.wjstar.xiaohashu.auth.domain.mapper: debug


aliyun: # 接入阿里云 发送短信使用
  accessKeyId: xxx
  accessKeySecret: xxx