#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================

storage:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: wujiedeyouxi
    secretKey: wujiedeyouxi
  aliyun-oss:
    endpoint: oss-ch-hangzhou.aliyuncs.com
    accessKey: xxxx
    secretKey: xxxxx